# Generated by Django 4.0.5 on 2022-06-23 11:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_suggestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
