# Generated by Django 4.0.5 on 2022-06-23 12:02

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_suggestion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='content',
            field=froala_editor.fields.FroalaField(default=''),
        ),
    ]
