# Generated by Django 4.0.5 on 2022-06-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_suggestion_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='image',
        ),
    ]
